const projects = [
  {
    id: 1,
    name: "Checkers Game",
    img: "/images/checkers.png",
    site: "https://checkersgame.netlify.app",
    repository: "https://github.com/thechiefishere/Checkers",
    type: "Game",
    featured: true,
    technologies: [
      "Socket.io",
      "NodeJS",
      "Express",
      "Mongo",
      "Redux",
      "React",
      "Sass",
    ],
  },
  {
    id: 2,
    name: "Tokunbo Cars",
    img: "/images/tokunbo.png",
    site: "https://tokunbocars.netlify.app",
    repository: "https://github.com/thechiefishere/tokunboCars",
    type: "E-commerce",
    featured: true,
    technologies: ["NodeJS", "Express", "Mongo", "React", "Sass"],
  },
  {
    id: 3,
    name: "Bata",
    img: "/images/bata.png",
    site: "https://buy-bata.netlify.app",
    repository: "https://github.com/thechiefishere/Bata",
    type: "E-commerce",
    featured: true,
    technologies: ["NodeJS", "Express", "Mongo", "React", "Redux", "Sass"],
  },
  {
    id: 4,
    name: "BFS vs DFS",
    img: "/images/bfsvsdfs.png",
    site: "https://bfsvsdfs.netlify.app/home",
    repository: "https://github.com/thechiefishere/BfsvsDfs",
    type: "Algorithm",
    featured: true,
    technologies: ["React", "Sass"],
  },
  {
    id: 5,
    name: "Affordable Services",
    img: "/images/affordable.png",
    site: "https://affordableservices.netlify.app/home",
    repository: "https://github.com/thechiefishere/AffordablesReact",
    type: "E-commerce",
    featured: true,
    technologies: ["React", "Sass"],
  },
  {
    id: 6,
    name: "Snake Game",
    img: "/images/snake.png",
    site: "https://simplesnake-game.netlify.app/home",
    repository: "https://github.com/thechiefishere/Snake-Game",
    type: "Game",
    featured: true,
    technologies: ["React", "Sass"],
  },
  {
    id: 7,
    name: "CocktailDb",
    img: "/images/cocktail.png",
    site: "https://github.com/thechiefishere/Cocktails",
    repository: "https://github.com/thechiefishere/Cocktails",
    type: "E-commerce",
    featured: false,
    technologies: ["React", "Sass"],
  },
  {
    id: 8,
    name: "Cart",
    img: "/images/cart.png",
    site: "https://cartsandreducer.netlify.app/",
    repository: "https://github.com/thechiefishere/Cart",
    type: "Practice",
    featured: false,
    technologies: ["React", "Sass"],
  },
  {
    id: 9,
    name: "Grocery Bud",
    img: "/images/grocery-bud.png",
    site: "https://github.com/thechiefishere/Grocery-Bud",
    repository: "https://github.com/thechiefishere/Grocery-Bud",
    type: "Practice",
    featured: false,
    technologies: ["React", "Sass"],
  },
];

export default projects;
